"""Single source of truth for every cut, hit and label time in EARTH, SO FAR.

Run:  python3 audio/timeline.py   → writes audio/timeline.json and timeline.js
Both the score (audio/score.py) and the picture (index.html) read these numbers,
so a cut can never drift from the music.
"""
import json, math, os

BPM = 96.0
BEAT = 60.0 / BPM          # 0.625 s
BAR = 4 * BEAT             # 2.5 s
DURATION = 120.0

# Human-montage accelerando: tempo ramps linearly so that exactly 28 beats
# fit between 75.0 s and 88.0 s ("NOW").
M0, M1, M_BEATS = 75.0, 88.0, 28
M_BPM0 = BPM
M_BPM1 = 2 * M_BEATS * 60.0 / (M1 - M0) - M_BPM0   # ≈ 162.46


def montage_beat_time(k):
    """Time of beat k (0..28) under the linear tempo ramp."""
    L = M1 - M0
    a = (M_BPM1 - M_BPM0) / (2 * L * 60.0)
    b = M_BPM0 / 60.0
    c = -k
    if abs(a) < 1e-12:
        return M0 - c / b
    tau = (-b + math.sqrt(b * b - 4 * a * c)) / (2 * a)
    return M0 + tau


MONTAGE_BEATS = [round(montage_beat_time(k), 4) for k in range(M_BEATS + 1)]

# Scenes (engine programs) — start/end in seconds.
SCENES = [
    ("dust", 0.0, 5.0),
    ("molten", 5.0, 12.5),
    ("theia", 12.5, 17.5),
    ("moonrise", 17.5, 22.5),
    ("storm", 22.5, 25.0),
    ("ocean", 25.0, 30.0),
    ("cells", 30.0, 37.5),
    ("oxygen", 37.5, 42.5),
    ("snowball", 42.5, 47.5),
    ("cambrian", 47.5, 53.75),
    ("greenworld", 53.75, 60.0),
    ("ash", 60.0, 65.0),
    ("branch", 65.0, 70.0),
    ("fire", 70.0, 72.5),
    ("hand", 72.5, 75.0),
    ("montage", 75.0, 88.0),
    ("now", 88.0, 90.0),
    ("co2", 90.0, 97.5),
    ("bluemarble", 97.5, 100.0),
    ("boil", 100.0, 105.0),
    ("redgiant", 105.0, 112.0),
    ("end", 112.0, 120.0),
]

HITS = {
    "drop": 5.0,
    "theia_impact": 15.0,
    "lightning": [22.62, 23.35, 24.18],
    "cambrian": 47.5,
    "asteroid_riser": 58.75,
    "asteroid_impact": 59.8,
    "silence_1": 60.0,
    "bell_survivor": 62.5,
    "now": 88.0,
    "chart_draw": [90.6, 95.0],
    "spike_end": 95.45,
    "future": 100.0,
    "sun_rise": 105.0,
    "flare": 111.0,
    "silence_2": 112.0,
    "line_1": 112.6,
    "line_2": 115.7,
    "title": 117.6,
}

# Montage plates: (beat index, key, label). Each plate holds until the next.
MONTAGE = [
    (0, "farming", "12,000 YEARS AGO · FARMING"),
    (4, "cuneiform", "c. 3100 BCE · WRITING"),
    (8, "pyramid", "2560 BCE · THE GREAT PYRAMID"),
    (11, "gutenberg", "1450s · THE PRINTING PRESS"),
    (14, "coalbrookdale", "1760s · INDUSTRY"),
    (16, "first_flight", "1903 · FLIGHT"),
    (18, "trinity", "1945 · THE ATOMIC AGE"),
    (20, "earthrise", "1968 · EARTHRISE"),
    (22, "bootprint", "1969 · THE MOON"),
    (24, "web", "1991 · THE WEB"),
    (25, "flash1", ""),
    (26, "flash2", ""),
    (27, "flash3", ""),
]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    data = dict(bpm=BPM, beat=BEAT, bar=BAR, duration=DURATION,
                montage=dict(t0=M0, t1=M1, beats=MONTAGE_BEATS, bpm0=M_BPM0, bpm1=M_BPM1,
                             plates=[dict(beat=b, t=MONTAGE_BEATS[b], key=k, label=l) for b, k, l in MONTAGE]),
                scenes=[dict(id=i, start=s, end=e) for i, s, e in SCENES], hits=HITS)
    with open(os.path.join(here, "timeline.json"), "w") as f:
        json.dump(data, f, indent=1)
    with open(os.path.join(here, "..", "timeline.js"), "w") as f:
        f.write("// generated by audio/timeline.py — do not edit by hand\n")
        f.write("window.EARTH_TIMELINE = " + json.dumps(data) + ";\n")
    print("montage bpm1 = %.2f" % M_BPM1)
    print("beats:", MONTAGE_BEATS)


if __name__ == "__main__":
    main()
